pipeline {
    agent any
    tools {
        maven 'Maven 3' // Set this in Jenkins Global Tool Config
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/cnabi/simple-java-maven-app.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
